#!/bin/sh

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

dir=`dirname $0`
sed -i 's/package/root/' "$dir/../conf/privilege"

/usr/local/rc.d/dddvb-modules.sh start

if [ "$?" -eq 0 ]; then
    echo "DD DVB modules have been loaded successfully"
    exit 0
else
    echo "An error occurred during the loading of the DD DVB modules" 1>&2
    exit 1
fi
